# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_week', models.CharField(max_length=255)),
                ('assignment_engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.engagement')),
                ('assignment_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.resource')),
            ],
        ),
    ]
