# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='engagementID',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resourceID',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
