# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0003_auto_20170718_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientID', models.PositiveIntegerField(default=0, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_industry', models.CharField(max_length=255)),
                ('client_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='client_name',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_engagement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schedule.engagement'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schedule.resource'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='engagementID',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resourceID',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='clientID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Schedule.client'),
        ),
    ]
